trigger:
- main

pool:
  name: Default

steps:

- task: UseNode@1
  inputs:
    version: '18.x'

- script: npm install
  displayName: Install dependencies

- script: |
    echo Pipeline running successfully
    node -v
  displayName: Verify Node
