apiVersion: apps/v1
kind: Deployment

metadata:
  name: artstore-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: artstore-backend

  template:
    metadata:
      labels:
        app: artstore-backend

    spec:
      containers:
      - name: backend
        image: edithfloresiteso/artstore-backend
        ports:
        - containerPort: 3000